CREATE DATABASE IF NOT EXISTS chms_santa_rosa CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE chms_santa_rosa;
SET FOREIGN_KEY_CHECKS=0;
DROP TABLE IF EXISTS audit_logs, ocr_documents, health_records, vaccinations, appointments, residents, public_announcements, settings, role_permissions, permissions, users, roles, services;
SET FOREIGN_KEY_CHECKS=1;

CREATE TABLE roles (id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, name VARCHAR(80) NOT NULL UNIQUE, code VARCHAR(50) NOT NULL UNIQUE, description VARCHAR(255), is_system TINYINT(1) NOT NULL DEFAULT 1) ENGINE=InnoDB;
CREATE TABLE permissions (id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, code VARCHAR(100) NOT NULL UNIQUE, description VARCHAR(255)) ENGINE=InnoDB;
CREATE TABLE services (id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, name VARCHAR(120) NOT NULL UNIQUE, description TEXT, department VARCHAR(120), status ENUM('Active','Inactive') NOT NULL DEFAULT 'Active', public_booking_enabled TINYINT(1) NOT NULL DEFAULT 0, daily_capacity INT UNSIGNED NOT NULL DEFAULT 8, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP) ENGINE=InnoDB;
CREATE TABLE role_permissions (role_id INT UNSIGNED NOT NULL, permission_id INT UNSIGNED NOT NULL, PRIMARY KEY(role_id,permission_id), FOREIGN KEY(role_id) REFERENCES roles(id) ON DELETE CASCADE, FOREIGN KEY(permission_id) REFERENCES permissions(id) ON DELETE CASCADE) ENGINE=InnoDB;
CREATE TABLE users (id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, staff_id VARCHAR(50) NOT NULL UNIQUE, full_name VARCHAR(180) NOT NULL, email VARCHAR(190) NOT NULL UNIQUE, password_hash VARCHAR(255) NOT NULL, role_id INT UNSIGNED NOT NULL, service_id INT UNSIGNED NULL, professional_type VARCHAR(100), license_no VARCHAR(100), status ENUM('Active','Inactive') NOT NULL DEFAULT 'Active', last_login_at DATETIME NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, FOREIGN KEY(role_id) REFERENCES roles(id), FOREIGN KEY(service_id) REFERENCES services(id) ON DELETE SET NULL, INDEX(role_id), INDEX(service_id));
CREATE TABLE residents (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, patient_id VARCHAR(30) NOT NULL UNIQUE, first_name VARCHAR(100) NOT NULL, middle_name VARCHAR(100), last_name VARCHAR(100) NOT NULL, suffix VARCHAR(20), birth_date DATE NOT NULL, sex ENUM('Male','Female','Other') NOT NULL, civil_status ENUM('Single','Married','Separated','Widowed','Divorced') NULL, contact_number VARCHAR(40), email VARCHAR(190), address TEXT, barangay VARCHAR(100) NOT NULL, citizenship VARCHAR(80) DEFAULT 'Filipino', occupation VARCHAR(120), emergency_contact VARCHAR(180), emergency_contact_number VARCHAR(40), registered_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, status ENUM('Active','Archived') NOT NULL DEFAULT 'Active', created_by INT UNSIGNED NULL, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, FOREIGN KEY(created_by) REFERENCES users(id) ON DELETE SET NULL, INDEX(barangay), INDEX(last_name), INDEX(first_name), INDEX(status));
CREATE TABLE appointments (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, reference_no VARCHAR(40) NOT NULL UNIQUE, resident_id BIGINT UNSIGNED NULL, service_id INT UNSIGNED NOT NULL, appointment_date DATE NOT NULL, appointment_time TIME NOT NULL, assigned_staff_id INT UNSIGNED NULL, purpose VARCHAR(255), vaccine_type VARCHAR(120), status ENUM('Pending','Scheduled','Completed','Cancelled','No-show') NOT NULL DEFAULT 'Pending', created_by INT UNSIGNED NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, FOREIGN KEY(resident_id) REFERENCES residents(id) ON DELETE SET NULL, FOREIGN KEY(service_id) REFERENCES services(id), FOREIGN KEY(assigned_staff_id) REFERENCES users(id) ON DELETE SET NULL, FOREIGN KEY(created_by) REFERENCES users(id) ON DELETE SET NULL, INDEX(appointment_date), INDEX(assigned_staff_id), INDEX(status));
CREATE TABLE health_records (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, resident_id BIGINT UNSIGNED NOT NULL, service_id INT UNSIGNED NOT NULL, record_type VARCHAR(100) NOT NULL, record_date DATE NOT NULL, assigned_staff_id INT UNSIGNED NULL, diagnosis_summary TEXT, notes TEXT, status ENUM('Active','Archived') NOT NULL DEFAULT 'Active', created_by INT UNSIGNED NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, FOREIGN KEY(resident_id) REFERENCES residents(id), FOREIGN KEY(service_id) REFERENCES services(id), FOREIGN KEY(assigned_staff_id) REFERENCES users(id) ON DELETE SET NULL, FOREIGN KEY(created_by) REFERENCES users(id) ON DELETE SET NULL, INDEX(record_date), INDEX(assigned_staff_id), INDEX(service_id));
CREATE TABLE vaccinations (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, resident_id BIGINT UNSIGNED NOT NULL, vaccine VARCHAR(120) NOT NULL, dose VARCHAR(60), administered_date DATE NOT NULL, administered_by INT UNSIGNED NULL, notes TEXT, status ENUM('Active','Archived') NOT NULL DEFAULT 'Active', created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, FOREIGN KEY(resident_id) REFERENCES residents(id), FOREIGN KEY(administered_by) REFERENCES users(id) ON DELETE SET NULL, INDEX(administered_date), INDEX(vaccine));
CREATE TABLE health_programs (id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, name VARCHAR(160) NOT NULL UNIQUE, description TEXT, start_date DATE NULL, end_date DATE NULL, status ENUM('Planned','Active','Completed','Archived') NOT NULL DEFAULT 'Planned', created_by INT UNSIGNED NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, FOREIGN KEY(created_by) REFERENCES users(id) ON DELETE SET NULL);
CREATE TABLE ocr_documents (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, file_name VARCHAR(255) NOT NULL, stored_path VARCHAR(500) NOT NULL, extracted_text LONGTEXT, status ENUM('Uploaded','Extracted','Verified','Rejected') NOT NULL DEFAULT 'Uploaded', verified_by INT UNSIGNED NULL, verified_at DATETIME NULL, created_by INT UNSIGNED NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY(verified_by) REFERENCES users(id) ON DELETE SET NULL, FOREIGN KEY(created_by) REFERENCES users(id) ON DELETE SET NULL);
CREATE TABLE public_announcements (id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, title VARCHAR(200) NOT NULL, content TEXT NOT NULL, publish_date DATE NOT NULL, expiry_date DATE NULL, status ENUM('Draft','Published','Archived') NOT NULL DEFAULT 'Draft', created_by INT UNSIGNED NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, FOREIGN KEY(created_by) REFERENCES users(id) ON DELETE SET NULL);
CREATE TABLE settings (id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, setting_key VARCHAR(100) NOT NULL UNIQUE, setting_value VARCHAR(255) NOT NULL);
CREATE TABLE audit_logs (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, user_id INT UNSIGNED NULL, action VARCHAR(80) NOT NULL, entity VARCHAR(80), entity_id BIGINT UNSIGNED NULL, description TEXT, ip_address VARCHAR(45), created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE SET NULL, INDEX(action), INDEX(created_at));

INSERT INTO roles(name,code,description) VALUES
('System Administrator','ADMIN','Full system administration'),('Doctor','DOCTOR','Assigned clinical patients and records'),('Nurse','NURSE','Nursing and immunization workflows'),('Dentist','DENTIST','Dental service workflows'),('Pharmacist','PHARMACIST','Pharmacy workflows'),('Laboratory Staff','LAB','Laboratory workflows'),('ABTC Staff','ABTC','ABTC workflows'),('Psychiatrist','PSYCHIATRIST','Restricted mental health workflows'),('General Staff','STAFF','Administrator-assigned operational access'),('Barangay Health Worker','BHW','Barangay community health workflows');

INSERT INTO permissions(code,description) VALUES
('dashboard.view','View dashboard'),('residents.view','View residents'),('residents.create','Create residents'),('residents.edit','Edit residents'),('residents.delete','Archive/restore residents'),
('appointments.view','View appointments'),('appointments.create','Create appointments'),('appointments.edit','Edit appointments'),('appointments.delete','Cancel appointments'),
('records.view','View health records'),('records.create','Create health records'),('records.edit','Edit health records'),('records.delete','Archive health records'),
('vaccinations.view','View vaccinations'),('vaccinations.create','Create vaccinations'),('vaccinations.edit','Edit vaccinations'),('vaccinations.delete','Archive vaccinations'),
('reports.view','View reports'),('analytics.view','View analytics'),('ocr.view','Use OCR'),('ocr.verify','Verify/reject OCR'),('users.view','View users'),('users.create','Create users'),('users.edit','Edit users'),('users.delete','Deactivate users'),('services.manage','Manage services'),('programs.manage','Manage programs'),('announcements.manage','Manage announcements'),('settings.manage','Manage settings'),('audit.view','View audit logs');

INSERT INTO services(name,description,department,status,public_booking_enabled,daily_capacity) VALUES
('OPD','Outpatient Department','OPD','Active',0,8),('Dental','Dental services','Dental','Active',1,8),('Pharmacy','Medication dispensing and pharmacy services','Pharmacy','Active',0,8),('ABTC','Animal Bite Treatment Center','ABTC','Active',0,8),('Laboratory','Laboratory testing','Laboratory','Active',0,8),('Psychiatry / Mental Health','Mental health services','Mental Health','Active',0,8),('Nursing','Nursing services','Nursing','Active',0,8),('Immunization','Vaccination and immunization','Immunization','Active',1,8),('Maternal and Child Health','Maternal and child health','MCH','Active',0,8),('Nutrition','Nutrition services','Nutrition','Active',0,8),('TB / DOTS','Tuberculosis treatment and monitoring','TB / DOTS','Active',0,8),('Dengue / Disease Surveillance','Disease surveillance','Surveillance','Active',0,8),('Family Planning','Family planning services','Family Planning','Active',1,8),('Other CHO Services','Other City Health Office services','CHO','Active',0,8);
INSERT INTO settings(setting_key,setting_value) VALUES ('default_daily_capacity','8'),('session_timeout_seconds','1800');

-- Permissions for all roles are intentionally explicit. Restricted roles receive only needed capabilities.
INSERT INTO role_permissions(role_id,permission_id) SELECT r.id,p.id FROM roles r CROSS JOIN permissions p WHERE r.code='ADMIN';
INSERT INTO role_permissions(role_id,permission_id) SELECT r.id,p.id FROM roles r JOIN permissions p ON p.code IN ('dashboard.view','residents.view','appointments.view','records.view','records.create','records.edit','vaccinations.view','vaccinations.create','vaccinations.edit','reports.view','analytics.view') WHERE r.code='DOCTOR';
INSERT INTO role_permissions(role_id,permission_id) SELECT r.id,p.id FROM roles r JOIN permissions p ON p.code IN ('dashboard.view','residents.view','residents.create','residents.edit','appointments.view','appointments.create','appointments.edit','records.view','records.create','records.edit','vaccinations.view','vaccinations.create','vaccinations.edit','reports.view') WHERE r.code='NURSE';
INSERT INTO role_permissions(role_id,permission_id) SELECT r.id,p.id FROM roles r JOIN permissions p ON p.code IN ('dashboard.view','residents.view','appointments.view','appointments.create','appointments.edit','records.view','records.create','records.edit','reports.view') WHERE r.code='DENTIST';
INSERT INTO role_permissions(role_id,permission_id) SELECT r.id,p.id FROM roles r JOIN permissions p ON p.code IN ('dashboard.view','residents.view','appointments.view','records.view','records.create','records.edit','reports.view') WHERE r.code='PHARMACIST';
INSERT INTO role_permissions(role_id,permission_id) SELECT r.id,p.id FROM roles r JOIN permissions p ON p.code IN ('dashboard.view','residents.view','appointments.view','records.view','records.create','records.edit','reports.view') WHERE r.code='LAB';
INSERT INTO role_permissions(role_id,permission_id) SELECT r.id,p.id FROM roles r JOIN permissions p ON p.code IN ('dashboard.view','residents.view','appointments.view','records.view','records.create','records.edit','reports.view') WHERE r.code='ABTC';
INSERT INTO role_permissions(role_id,permission_id) SELECT r.id,p.id FROM roles r JOIN permissions p ON p.code IN ('dashboard.view','residents.view','appointments.view','records.view','records.create','records.edit','reports.view') WHERE r.code='PSYCHIATRIST';
INSERT INTO role_permissions(role_id,permission_id) SELECT r.id,p.id FROM roles r JOIN permissions p ON p.code IN ('dashboard.view','residents.view','appointments.view','records.view','reports.view') WHERE r.code='STAFF';
INSERT INTO role_permissions(role_id,permission_id) SELECT r.id,p.id FROM roles r JOIN permissions p ON p.code IN ('dashboard.view','residents.view','appointments.view','records.view','vaccinations.view','vaccinations.create','reports.view') WHERE r.code='BHW';

CREATE OR REPLACE VIEW v_appointment_capacity AS SELECT a.service_id,a.appointment_date,COUNT(*) total FROM appointments a WHERE a.status IN ('Pending','Scheduled') GROUP BY a.service_id,a.appointment_date;
